### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by JJBirdgender** [lt-name/MurderMystery_Nukkit#6]
Really love the plugin! It's great! Can I have the download link for the Shop addon, also do you know wether there's an English version for the Tips plugin? Thanks!

**Comment by JJBirdgender** [comment]
And I have a suggestion as well:
Add option in config for how many players needed

**Comment by lt-name** [comment]
UiShop addon:
set MurderMystery\Addons\config.yml  UiShop: true

Tips English version:
https://github.com/lt-name/MurderMystery_Nukkit/blob/master/lib/Tips_v1.6.8-English.jar

I personally think that this game has a minimum of 5 people is the best, and the game rules must be limited to 3 people, otherwise the plug-in will have an infinite loop problem
Maybe it can be adjusted down to a minimum of 3 people, but those games will become boring because it’s easy to guess the player’s identity
(Google Translate)

**Comment by JJBirdgender** [comment]
Yes I agree with how many players it needs actually lol, also I think you should make a hide and seek or Block Hunt plugin! That would be so cool and I think you could!

**Comment by lt-name** [comment]
If I have time, maybe I will try
